### ISSUE TITLE
Cannot transition from `scribe/edit` to `scribe/checkout` in Dashboard.

### ISSUE THREAD

**Issue by Harvest-Haven-Apps** [HarvestHaven/TPOT-Next#25]
Cannot transition from `scribe/edit` to `scribe/checkout` in Dashboard.

**Comment by Braden-Preston** [comment]
This will be fixed when the Dashboard component is updated to support navigation, current menu position, etc.. Right now I am prioritizing getting all the page templates wrapped into the same Dashboard layout.
